# This file is generated by kkensuke/slink. Do not edit it manually.
class Slink < Formula
  desc "A symbolic-link management CLI for macOS"
  homepage "https://github.com/kkensuke/slink"
  url "https://github.com/kkensuke/slink/archive/refs/tags/v0.2.3.tar.gz"
  sha256 "d4aaa30d674bb558e6a57ba989149dc98f4ea5c44b5d2c3965b49b588ca4c391"
  license "MIT"

  depends_on "rust" => :build
  depends_on :macos

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slink --version")

    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    target = testpath/"target"
    target.write "hello"
    link = testpath/"links/example"

    system bin/"slink", "--parents", target.to_s, link.to_s
    assert_predicate link, :symlink?
    assert_equal target.to_s, link.readlink.to_s
    system bin/"slink", "check", link.to_s
  end
end
