# This file is generated by kkensuke/slink. Do not edit it manually.
class Slink < Formula
  desc "Managed symbolic-link CLI for macOS"
  homepage "https://github.com/kkensuke/slink"
  url "https://github.com/kkensuke/slink/archive/refs/tags/v0.2.1.tar.gz"
  sha256 "beb88faecf2f01f1b3ec5223d1872f46cf324ec0250d21e6dd50e0d43959c3a8"
  license "MIT"

  depends_on "rust" => :build
  depends_on :macos

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slink --version")

    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    target = testpath/"target"
    target.write "hello"
    link = testpath/"links/example"

    system bin/"slink", "--parents", target.to_s, link.to_s
    assert_predicate link, :symlink?
    assert_equal target.to_s, link.readlink.to_s
    system bin/"slink", "check", link.to_s
  end
end
