# This file is generated by kkensuke/slink. Do not edit it manually.
class Slink < Formula
  desc "Managed symbolic-link CLI for macOS"
  homepage "https://github.com/kkensuke/slink"
  url "https://github.com/kkensuke/slink/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "d8c4014b9d304abc8e6fd2f37906e56b93b32090cd36ec6a7571ee519d3e9c46"
  license "MIT"

  depends_on "rust" => :build
  depends_on :macos

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slink --version")

    ENV["XDG_CONFIG_HOME"] = (testpath/"config").to_s
    target = testpath/"target"
    target.write "hello"
    link = testpath/"links/example"

    system bin/"slink", "--parents", target.to_s, link.to_s
    assert_predicate link, :symlink?
    assert_equal target.to_s, link.readlink.to_s
    system bin/"slink", "check", link.to_s
  end
end
